import os

OUTPUT_DIRECTORY = os.path.join("output", "generated")
LOG_DIRECTORY = "logs"
DEFAULT_ASSET_DOMAIN = "https://assets.spacecases.xyz"
VANILLA_KNIVES = {
    "★ Bayonet",
    "★ Classic Knife",
    "★ Flip Knife",
    "★ Gut Knife",
    "★ Karambit",
    "★ M9 Bayonet",
    "★ Huntsman Knife",
    "★ Falchion Knife",
    "★ Bowie Knife",
    "★ Butterfly Knife",
    "★ Shadow Daggers",
    "★ Paracord Knife",
    "★ Survival Knife",
    "★ Ursus Knife",
    "★ Navaja Knife",
    "★ Nomad Knife",
    "★ Stiletto Knife",
    "★ Talon Knife",
    "★ Skeleton Knife",
    "★ Kukri Knife",
    "★ StatTrak™ Bayonet",
    "★ StatTrak™ Classic Knife",
    "★ StatTrak™ Flip Knife",
    "★ StatTrak™ Gut Knife",
    "★ StatTrak™ Karambit",
    "★ StatTrak™ M9 Bayonet",
    "★ StatTrak™ Huntsman Knife",
    "★ StatTrak™ Falchion Knife",
    "★ StatTrak™ Bowie Knife",
    "★ StatTrak™ Butterfly Knife",
    "★ StatTrak™ Shadow Daggers",
    "★ StatTrak™ Paracord Knife",
    "★ StatTrak™ Survival Knife",
    "★ StatTrak™ Ursus Knife",
    "★ StatTrak™ Navaja Knife",
    "★ StatTrak™ Nomad Knife",
    "★ StatTrak™ Stiletto Knife",
    "★ StatTrak™ Talon Knife",
    "★ StatTrak™ Skeleton Knife",
    "★ StatTrak™ Kukri Knife",
}
