name: Assets Services CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checks:
    uses: Spacerulerwill/SpaceCases/.github/workflows/checks.yml@master
    with:
      path: "services/assets"
  docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build image
        run: |
          cd services/assets
          docker build -f Dockerfile ../../