name: Codespell

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Spellcheck
        uses: codespell-project/actions-codespell@v2